fix syntax error in CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -754,11 +754,13 @@ jobs:
         run: |
           timeout 600 bash -c 'until curl -sf http://localhost:3000/health; do sleep 2; done'
       - name: Verify OGC API endpoint exists
-        run: curl -sf http://localhost:3000/ogc/ > /dev/null || { echo "ERROR: OGC API not available"; exit 1; }
+        run: |
+          curl -sf http://localhost:3000/ogc/ > /dev/null || { echo "ERROR: OGC API not available"; exit 1; }
       - name: Start teamengine
         run: docker run -d --network=host ogccite/teamengine-production:1.0-SNAPSHOT
       - name: Verify teamengine API endpoint exists
-        run: curl -sf http://localhost:8080/teamengine > /dev/null || { echo "ERROR: OGC API not available"; exit 1; }
+        run: |
+          curl -sf http://localhost:8080/teamengine > /dev/null || { echo "ERROR: OGC API not available"; exit 1; }
       - name: test ogcapi-tiles compliancy
         uses: OSGEO/ogc-cite-runner@v0.3.1
         with:
